server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimeZone=Asia/Shanghai&charEncoding=utf-8
    username: root
    password: 116924

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  expiration: 10
  head: Bearer
  secret: token