server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?serverTimeZone=Asia/Shanghai&charEncoding=utf-8
    username: root
    password: 116924
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  expiration: 604800  # 7*24*60*60S
  secret: token
  tokenHeader: Authorization
  tokenHead: 'Bearer'

security:
  ignored:
    urls:
      - /swagger-ui/
      - /swagger**
      - /swagger-ui/**
      - /swagger-resources/**
      - /**/v2/api-docs
      - /v3/**
      - /webjars**
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

redis:
  database: mall
  expire: 806400 #24*3600S
  host: 47.92.248.145
  port: 6379
  password:
  key:
    admin: "ums:admin"
    resourceList: "ums:resourceList"
    orderId: "oms:orderId"